apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: {{ .Values.global.argocdNamespace | quote }}
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.appsNamespace | quote }}
  source:
    repoURL: ghcr.io/stefanprodan/charts
    chart: podinfo
    targetRevision: {{ .Values.podinfo.version | quote }}
    helm:
      releaseName: podinfo
      values: |
        ingress:
          enabled: true
          className: {{ .Values.global.ingressClassName | quote }}
          hosts:
            - host: {{ default (printf "podinfo.%s" .Values.global.hostSuffix) .Values.podinfo.host | quote }}
              paths:
                - path: /
                  pathType: ImplementationSpecific
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
