apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  source:
    repoURL: https://github.com/melamed777/surf-task
    targetRevision: main
    path: charts/generic-app
    helm:
      releaseName: app2
      values: |
        image:
          repository: ghcr.io/melamed777/app2
          tag: latest
        ingress:
          enabled: true
          className: nginx
          host: app2.localtest.me
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
