apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  source:
    repoURL: ghcr.io/stefanprodan/charts
    chart: podinfo
    targetRevision: 6.7.0
    helm:
      releaseName: podinfo
      values: |
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: podinfo.localtest.me
              paths:
                - path: /
                  pathType: ImplementationSpecific
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
